{
 "title": "Service Overview (RED metrics)",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "p95 latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (service_name, le) (rate(http_server_request_duration_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (service_name) (rate(http_server_request_duration_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC client failed calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (service_name, rpc_grpc_status_code) (rate(rpc_client_call_duration_seconds_count{rpc_grpc_status_code!=\"0\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Order outcomes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (outcome) (rate(order_place_order_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}